myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    # path('', views.home, name='Home'),
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('products', views.products, name='products'),
    path('products/<prod_id>',views.productdetail,name='productdetail'),
    path('placeorder/<prod_id>', views.place_order, name='placeorder'),
    path('login/',views.login,name='login'),
    path('login/user_login',views.user_login,name='userlogin'),
    path('myorders',views.myorders,name='myorders'),
    path('logout',views.user_logout,name='userlogout'),
    path('detail/<int:cat_id>',views.detail,name='detail'),
    path('register',views.register,name='register'),
    ]

mysiteS19/urls.py
from django.contrib import admin
from django.urls import include, path
from mysiteS19 import views

urlpatterns = [
    path('', views.home, name='Home'),
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator



class Category(models.Model):
    name = models.CharField(max_length=200)
    warehouse = models.CharField(max_length=10, default='Windsor')

    def __str__(self):
        return self.name + ", " + self.warehouse


class Product(models.Model):
    Category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=100, validators=[MaxValueValidator(1000), MinValueValidator(0)])
    available = models.BooleanField(default=True)
    interested = models.PositiveIntegerField(default=0)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    def refill(self):
        stock = self.stock + 50
        if(stock >= 0):
            if(stock <= 1000):
                t = Product.objects.get(id=self.id)
                t.stock = stock
                t.save()
                return 1
            else:
                return 0
        else:
            return 0


    def getCategory(self):
        return self.Category.name


class Client(User):
    PROVINCE_CHOICES = [
         ('AB', 'Alberta'),
         ('MB', 'Manitoba'),
         ('ON', 'Ontario'),
         ('QC', 'Quebec'),
    ]
    company = models.CharField(max_length=50, null=True, blank=True)
    shipping_address = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    Interested_in = models.ManyToManyField(Category)

    def __str__(self):
        return self.first_name + " " + self.last_name

    def interested_in(self):
        list = []
        interested = Client.objects.filter(username=self.username).values("Interested_in__name")
        for a in interested:
            list.append(a['Interested_in__name'])
        return list


class Order(models.Model):
    INT_CHOICES = [
        (0, 'Order Cancelled'),
        (1, 'Order Placed'),
        (2, 'Order Shipped'),
        (3, 'Order Delivered')
    ]
    Product = models.ForeignKey(Product, related_name='orders', on_delete=models.CASCADE)
    Client = models.ForeignKey(Client, related_name='orders', on_delete=models.CASCADE)
    num_units = models.PositiveIntegerField(default=0)
    order_status = models.PositiveIntegerField(choices=INT_CHOICES, default=1)
    status_date = models.DateField(default='2019-05-01')

    def __str__(self):
        return 'Order#' + str(self.id) + ': For ' + ' ' + self.Product.name + " by " + str(self.Client)

    def total_cost(self):
        return self.Product.price * self.num_unit

myapp/views.py
from django.shortcuts import render,redirect, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect, HttpResponse
from .models import Category, Product, Client, Order
from .form import OrderForm, InterestForm, RegisterForm
from django.shortcuts import render
from django.utils import timezone
import datetime
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test


def index(request):
    if request.session.has_key('username'):
        username = request.session['username']
        client = Client.objects.get(username=username)
        inCat = client.Interested_in.all()
        lastLogin = request.session['last_login']
        return render(request, 'myapp/index.html', {'client': client, 'inCat': inCat, 'last_login': lastLogin})
    else:
        request.session['url'] = 'myapp:index'
        return redirect('myapp:login')


def about(request):
    if request.session.has_key('username'):
        username = request.session['username']
        client = Client.objects.get(username=username)
        cookieValue = request.COOKIES.get('about_visits', 'default')
        if(cookieValue == 'default'):
            response = render(request, 'myapp/about.html', {'client': client, 'about_visits':'1'})
            response.set_cookie('about_visits', 1, 5*60)
        else:
            cookieValue=int(cookieValue)+1
            response = render(request, 'myapp/about.html', {'client': client, 'about_visits': cookieValue})
            response.set_cookie('about_visits', cookieValue)
        return response
    else:
        request.session['url'] = 'myapp:about'
        return redirect('myapp:login')


def detail(request, cat_id):
    if request.session.has_key('username'):
        username = request.session['username']
        client = Client.objects.get(username=username)
        category = Category.objects.filter(id=cat_id)
        products = Product.objects.filter(Category__id=cat_id)
        print(category)
        print(products)
        return render(request, 'myapp/detail.html', {'client': client, 'category': category, 'products': products})
    else:
        request.session['url'] = 'myapp:detail'
        return redirect('myapp:login')


def products(request):
    if request.session.has_key('username'):
        username = request.session['username']
        client = Client.objects.get(username=username)
        products = Product.objects.all().order_by('id')[:10]
        return render(request, 'myapp/products.html', {'client': client, 'products': products})
    else:
        request.session['url'] = 'myapp:products'
        return redirect('/myapp/login')


def place_order(request, prod_id):
    if request.session.has_key('username'):
        msg = ''
        username = request.session['username']
        prod = Product.objects.get(id=prod_id)
        products = Product.objects.all()
        client = Client.objects.get(username=username)
        if request.method == 'POST':
            form = OrderForm(request.POST)
            if form.is_valid():
                order = form.save(commit=False)
                if order.num_units <= order.Product.stock:
                    order.save()
                    p = Product.objects.get(name=order.Product.name)
                    p.stock = order.Product.stock - order.num_units
                    p.save()
                    msg = 'Your order has been placed successfully.'
                else:
                    msg = 'We do not have sufficient stock to fill your order.'
                return render(request, 'myapp/orderresponse.html', {'msg': msg})
        else:
            form = OrderForm()
            return render(request, 'myapp/placeorder.html', {'client': client, 'form': form, 'msg': msg,
                                                             'products': products, 'prod': prod})
    else:
        request.session['url'] = 'myapp:place_order'
        return redirect('/myapp/login')


def productdetail(request, prod_id):
    if request.session.has_key('username'):
        product = Product.objects.get(id=prod_id)
        if request.method == 'POST':
            form = InterestForm(request.POST)
            if form.is_valid():
                if form.cleaned_data['interested'] == 1:
                    product.interested = product.interested + form.cleaned_data['interested']
                    product.save()
            return redirect('/myapp/')
        else:
            form = InterestForm()
            return render(request, 'myapp/productdetail.html', {'form': form, 'product': product})
    else:
        request.session['url'] = 'myapp:productdetail'
        return redirect('myapp:login')


def login(request):
    if request.session.has_key('username'):
        return redirect('myapp:index')
    else:
        request.session['url'] = 'myapp:index'
        return render(request, 'myapp/login.html')


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        useres = Client.objects.filter(username=username, password=password)
        if useres:
            user = useres.get(username=username, password=password)
            if user:
                now = datetime.datetime.now()
                lastlogin = now.strftime("%m/%d/%Y, %H:%M:%S")
                if user.is_active:
                    request.session['username'] = username
                    if not request.session.has_key('last_login'):
                        lastlogin = 'Your last login was more than one hour ago'
                        request.session['last_login'] = lastlogin
                    else:
                        request.session['last_login'] = lastlogin
                        request.session.set_expiry(3600)
                    if request.session.has_key('url'):
                        url = request.session['url']
                        return redirect(url)
                    else:
                        request.session['url'] = 'myapp:index'
                        return redirect('myapp:index')
                else:
                    request.session['url'] = 'myapp:index'
                    return redirect('myapp:register')
            else:
                return redirect('myapp:login')
        else:
            return render(request, 'myapp/invalid.html')
    else:
        return render(request, 'myapp/login.html')


def user_logout(request):
    del request.session['username']
    del request.session['url']
    return redirect('myapp:login')


def myorders(request):
    if request.session.has_key('username'):
        username = request.session['username']
        client = Client.objects.get(username=username)
        # client = Client.objects.get(id=user.id)
        myOrders = Order.objects.filter(Client__username=username)
        if myOrders:
            return render(request, 'myapp/myorders.html', {'client': client, 'myOrders': myOrders})
        else:
            return HttpResponse('You are not a registered client')
    else:
        request.session['url'] = 'myapp:myorders'
        return redirect('myapp:login')


def register(request):
    if request.session.has_key('username'):
        username = request.session['username']
        client = Client.objects.get(username=username)
        if client.is_active:
            return redirect('myapp:index')
        else:
            form = RegisterForm(request.POST)
            if request.method == 'POST':
                if form.is_valid():
                    if form.cleaned_data['register'] == True:
                        client.is_active = form.cleaned_data['register']
                        client.save()
                        return redirect('myapp:index')
                    else:
                        return redirect('myapp:register')
                else:
                    return redirect('myapp:register')
            form = RegisterForm()
            return render(request, 'myapp/register.html', {'form': form, 'client': client})
    else:
        request.session['url'] = 'myapp:index'
        return redirect('myapp:login')

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block title %}About!{% endblock %}
<h1>
    {% block myhdg %}
        Hello {{ client.first_name }}
    {% endblock %}
</h1>
{% block body_block %}
    <body>
        <div class="row">
            <div class="col"></div>
            <div class="col">
                <h2>This is an Online Store APP</h2>
                <strong>This app is developed by :</strong>
                    <ul class="list-group">
                        <li class="list-group-item text-danger">Arif Ahmed Ayon</li>
                        <li class="list-group-item text-primary">Nancy Gupta</li>
                        <li class="list-group-item text-success">Silkita Chauhan</li>
                        <li class="list-group-item text-secondary">Sowmya Budampati</li>
                    </ul>
                <p style="margin-top: 15px">Page visited: {{about_visits}}</p>
                </br>
                <a class="btn btn-danger" href="{% url 'myapp:index' %}">Back</a>
            </div>
            <div class="col"></div>
        </div>
    </body>
{% endblock %}

myapp/templates/myapp/about0.html
<html>
<head lang="en"> <meta charset="UTF-8">
    <title>About Page</title>
<body>
<h2>This is an Online Store APP</h2>
<p>
    <a href="./">Main page</a>
</p>
</body>
</head>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/css/bootstrap.min.css' %}" />
    <title>Online Store APP - {% block title %}Welcome!{% endblock %}</title>
</head>
<body>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="height: 50px">
         <a class="navbar-brand" href="{% url 'myapp:index' %}">{% block myhdg %}Hello{% endblock %}</a>
         <ul class="navbar-nav ml-auto" style="margin-top: 25px">
             {% if request.session.username %}
                 <li class="nav-item active">
                     <a class="nav-link" href="{% url 'myapp:about' %}">About</a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link" href = "{% url 'myapp:products' %}">Products</a><br/>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link" href = "{% url 'myapp:myorders' %}">My orders</a><br/>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link" href = "{% url 'myapp:userlogout' %}">Logout</a><br/>
                 </li>
             {% else %}
                 <li class="nav-item active">
                     <a class="nav-link" href = "{% url 'myapp:login' %}">Login</a><br/>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link" href = "{% url 'myapp:register' %}">Register</a>
                 </li>
             {% endif %}
         </ul>
     </nav>
     <div class="container-fluid align-items-center" style="min-height: 450px; margin-top: 25px">
         {% block body_block %}
         {% endblock %}
     </div>
     <hr />
     <footer class="page-footer font-small bg-dark text-center text-white footer-copyright">
         <p>© {% now "M Y" %} Copyright: Group 3 <br> All rights reserved</p>
     </footer>
</body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block title %}Category Details!{% endblock %}
<h1>
    {% block myhdg %}
        Hello {{ client.first_name }}
    {% endblock %}
</h1>
{% block body_block %}
    <body>
        <div class="row">
            <div class="col"></div>
            <div class="col">
                {% if category %}
                {% for cat in category %}
                    <h4>Name: {{ cat.name }}</h4>
                    <h4>Warehouse: {{ cat.warehouse }}</h4>
                {% endfor %}
                {% else %}
                    <strong>There are no available categories!</strong>
                {% endif %}
                {% if products %}
                    <ol class="list-group">
                    {% for p in products %}
                        <li class="list-group-item">{{ p.name }}</li>
                    {% endfor %}
                    </ol>
                {% else %}
                    <strong>There are no available products!</strong>
                {% endif %}
                </br>
                <a class="btn btn-danger" href="{% url 'myapp:index' %}">Back</a>
            </div>
            <div class="col"></div>
        </div>
    </body>
{% endblock %}

myapp/templates/myapp/detail0.html
<html>
<head lang="en"> <meta charset="UTF-8">
    <title>Detail Page</title>
<body>
{% if category %}
    {% for cat in category %}
        <h2>Name: {{ cat.name }}</h2>
        <h2>Warehouse: {{ cat.warehouse }}</h2>
    {% endfor %}
{% else %}
    <strong>There are no available categories!</strong>
{% endif %}
{% if products %}
    <ol>
    {% for p in products %}
        <li>{{ p.name }}</li>
    {% endfor %}
    </ol>
{% else %}
    <strong>There are no available products!</strong>
{% endif %}
<p>
    <a href="myapp/index/">Main page</a>
</p>
</body>
</head>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block title %}Index!{% endblock %}
<h1>
    {% block myhdg %}
        Hello {{ client.first_name }}
    {% endblock %}
</h1>
{% block body_block %}
    <body>
            <div class="row">
                <div class="col"></div>
                <div class="col">
                    {% if inCat %}
                        <h2>List of Categories you are interested in:</h2>
                        <ol class="list-group">
                            {% for cat in inCat %}
                                <li class="list-group-item"><a href="/myapp/detail/{{ cat.id}}">{{ cat.name}}</a></li>
                            {% endfor %}
                        </ol>
                    {% else %}
                        <p>There are no available categories!</p>
                    {% endif %}
                    {% if last_login %}
                        <p>Last Login: {{last_login}}</p>
                    {% endif %}
                </div>
                <div class="col"></div>
            </div>
    </body>
{% endblock %}

myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html>
<head lang="en"> <meta charset="UTF-8">
    <title>Online Store APP</title>
</head>
<body>
{% if cat_list %}
    <h2>List of Categories</h2>
    <ol> {% for cat in cat_list %}
        <li><a href="/{{ cat.id}}">{{ cat.name}}</a>  </li>
    {% endfor %}
    </ol>
{% else %}
    <strong>There are no available categories!</strong>
{% endif %}
<p>
    <a href="./about">About page</a>
</p>
</body>
</html>

myapp/templates/myapp/invalid.html
{% extends 'myapp/base.html' %}
{% block title %}Invalid Login!{% endblock %}
<h1>
    {% block myhdg %}
        Hello {{ client.first_name }}
    {% endblock %}
</h1>
{% block body_block %}
    <body>
        <div class="row">
             <div class="col"></div>
             <div class="col">
                 <strong>Username and Password does not match</strong> <br>
                 <a class="btn btn-secondary" href="{% url 'myapp:login'%}" value="">Back to Login</a>
             </div>
             <div class="col"></div>
        </div>
    </body>
{% endblock %}

myapp/templates/myapp/myorders.html
{% extends 'myapp/base.html' %}
{% block title %}My Orders!{% endblock %}
<h1>
    {% block myhdg %}
        Hello {{ client.first_name }}
    {% endblock %}
</h1>
{% block body_block %}
    <body>
        <div class="row">
             <div class="col"></div>
             <div class="col">
                 {% if myOrders %}
                    <h1>List of Products</h1>
                    {% for m in myOrders %}
                        <ul class="list-group">
                            <li class="list-group-item">{{ m.Product}}</li>
                        </ul>
                    {% endfor %}
                {% else %}
                    <strong>There are no orders by you!</strong>
                {% endif %}
                </br>
                <a class="btn btn-danger" href="{% url 'myapp:index' %}">Back</a>
             </div>
             <div class="col"></div>
        </div>
    </body>
{% endblock %}

myapp/templates/myapp/orderresponse.html
{% extends 'myapp/base.html' %}
{% block title %}Order Response!{% endblock %}
<h1>
    {% block myhdg %}
        Hello {{ client.first_name }}
    {% endblock %}
</h1>
{% block body_block %}
    <body>
        <div class="row">
             <div class="col"></div>
             <div class="col">
                 <strong>Message: {{msg}} </strong>
             </div>
             <div class="col"></div>
        </div>
    </body>
{% endblock %}

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}
{% block title %}Place Order!{% endblock %}
<h1>
    {% block myhdg %}
        Hello {{ client.first_name }}
    {% endblock %}
</h1>
{% block body_block %}
    <body>
        <div class="row">
            <div class="col"></div>
            <div class="col">
                {% if prod %}
                    <h2>Product</h2>
                    <label>Name</label> : {{ prod.name }}
                    </br>
                    <label>Stoke</label> : {{prod.price}}
                {% else %}
                    <strong>There are no available products!</strong>
                {% endif %}
                </br>
                <a class="btn btn-danger" href="{% url 'myapp:products' %}">Back</a>
            </div>
            <div class="col">
                <h1>Place Order:</h1>
                <div>
                    <form action="../myapp/placeorder" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>Client Name:</label>
                            {{ form.Client }}
                        </div>
    {#                   {% for choice in form.Client %}#}
    {#                      <span class="radio">{{ choice.tag }}</span>#}
    {#                      {{ choice.choice_label }}#}
    {#                       <br/>#}
    {#                   {% endfor %}#}
                        <div class="form-group">
                            <label class="col-form-label">Product:</label>
                                {{ form.Product }}
                        </div>
                        <div class="form-group">
                            <label class="col-form-label">Quantity:</label>
                                {{ form.num_units }}
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Submit" class="save btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
            <div class="col"></div>
        </div>
    </body>
{% endblock %}

myapp/templates/myapp/productdetail.html
{% extends 'myapp/base.html' %}
{% block title %}Details of Product!{% endblock %}
<h1>
    {% block myhdg %}
        Hello {{ client.first_name }}
    {% endblock %}
</h1>
{% block body_block %}
    <body>
        <div class="row">
             <div class="col">
                 {% if product %}
                    <h2>Product Detail</h2>
                    <h4>Name: {{product.name}} </h4>
                    <h4>People Interested: {{product.interested}} </h4>
                    <h4>Price: {{product.price}} </h4>
                    {% if product.stock <= 0  %}
                        <h4>Message: Product Not available</h4>
                    {% else %}
                        <h4>Stock: {{ product.stock }}</h4>
                    {% endif %}
                {% endif %}
                <a class="btn btn-primary" type="button" href="../placeorder/{{ product.id }}">Place Order</a>
             </div>
             <div class="col">
                <form action="../products/{{product.id}}" method="post">
                    {% csrf_token %}
                    <label>Interested:</label>
                    {% for choice in form.interested %}
                       <span class="radio">{{ choice.tag }}</span>
                       {{ choice.choice_label }}
                    {% endfor %}
                    <br/><br/>
                    <label class="col-form-label">Quantity:</label>
                        {{ form.quantity }}
                    <br/><br/>
                    <label>Additinal Comments:</label>
                        {{ form.comments }}
                        <br/>
                    <div style="margin-left:7em;margin-top:1em;">
                        <input type="submit" value="Submit" class="save btn btn-primary">
                    </div>
                </form>
             </div>
             <div class="col"></div>
        </div>
    </body>
{% endblock %}

myapp/templates/myapp/products.html
{% extends 'myapp/base.html' %}
{% block title %}Products!{% endblock %}
<h1>
    {% block myhdg %}
        Hello {{ client.first_name }}
    {% endblock %}
</h1>
{% block body_block %}
<body>
    <div class="row">
         <div class="col"></div>
         <div class="col">
             {% if products %}
                 <h1>List of Products</h1>
                 <ol class="list-group">
                 {% for p in products %}
                     <li class="list-group-item">
                         <div class="row">
                            <div class="col"> {{ p.name}} </div>
                            <div class="col"></div>
                            <div class="col">
                                <a class="btn btn-sm" href="/myapp/products/{{ p.id }}"> Add to Interested </a>
                            </div>
                         </div>
                     </li>
                 {% endfor %}
                 </ol>
             {% else %}
                 <strong>There are no available Products!</strong>
             {% endif %}
             </br>
             <div>
                 <a class="btn btn-danger" type="button" href="{% url 'myapp:index' %}">Back</a>
             </div>
         </div>
         <div class="col"></div>
    </div>
</body>
{% endblock %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}
{% block title %}Register!{% endblock %}
<h1>
    {% block myhdg %}
        Hello {{ client.first_name }}
    {% endblock %}
</h1>
{% block body_block %}
    <body>
        <div class="row">
             <div class="col"></div>
             <div class="col">
                 <form action="../myapp/register" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Submit">
                </form>
             </div>
             <div class="col"></div>
        </div>
    </body>
{% endblock %}